# ASSIGNMEENT 5 NUMPY PART 2 - BY HARSH BADHAN
* Assigned on 6th Feb, 2025

Q.1 For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), Find

i. Sum of all elements

ii. Sum of all elements row-wise

iii. Sum of all elements column-wise

In [2]:
import numpy as np

gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
sum = gfg.sum()
print('Sum of all the elements of 2D Array: ',sum)

row_wise_Sum = gfg.sum(axis=1)
print('Sum of all the elements row wise: ',row_wise_Sum)

column_wise_Sum = gfg.sum(axis=0)
print('Sum of all the elements Column wise: ',column_wise_Sum)


Sum of all the elements of 2D Array:  45
Sum of all the elements row wise:  [[14]
 [16]
 [15]]
Sum of all the elements Column wise:  [[20  9 16]]


Q.2 (a)For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find

i. Sorted array

ii. Indices of sorted array

iii. 4 smallest elements

iv. 5 largest elements

(b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find

i. Integer elements only

ii. Float elements only

In [3]:
array = np.array([10, 52, 62, 16, 16, 54, 453])

sorted_array = np.sort(array)
print('Sorted array: ',sorted_array)

Sorted array:  [ 10  16  16  52  54  62 453]


In [4]:
indices = np.argsort(array)
print("The indices of sorted array: ",indices)

The indices of sorted array:  [0 3 4 1 5 2 6]


In [5]:
smallest_elements = np.partition(array, 4)[:4]
print("4 smallest elements: ",smallest_elements)

4 smallest elements:  [16 10 16 52]


In [12]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
largest_5 = np.sort(array)[-5:]
largest_5

array([1.2, 2. , 2. , 2.2, 3. ])

In [14]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

integer_mask = array.astype(int)
integer_elements = array[integer_mask]
integer_elements


array([1.2, 1.2, 2.2, 2.2, 2. , 2.2])

In [15]:
float_mask = array != array.astype(int)
float_elements = array[float_mask]
float_elements


array([1.2, 2.2])

# Q.3 You are given a weekly sales dataset and need to perform various operations using NumPy broadcasting.
a) Generate your unique sales dataset:
 Take the sum of the ASCII values of the initials of your first and last
name. Call this value X. (If your initials are A B → ASCII sum = 65
+ 66 = 131 → sales = [131, 181, 231, 281, 331].)
 Create a NumPy array sales with values [X, X+50, X+100, X+150,
X+200].


b) Compute your personalized tax rate as ((X % 5) + 5) / 100.
 Use broadcasting to apply this tax rate to each sales value.


c) Adjust sales based on discount:
 If sales < X+100, apply a 5% discount.
 If sales >= X+100, apply a 10% discount.


d) Expand sales data for multiple weeks:
 Create a 3×5 matrix representing three weeks of sales by stacking
sales three times using broadcasting.
 Increase sales by 2% per week using element-wise broadcasting.