# Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic operations like:
a) b) c) Addition of 2 in all the element
Multiply 3 with all the elements
Divide every element by 2

In [1]:
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr+ 2) #addition of 2

print(arr *3) #multiplication by 3

print(arr / 2) # division by 2

[3 4 5 6 7]
[ 3  6  9 12 15]
[0.5 1.  1.5 2.  2.5]


# Q.2 Questions on Basic NumPy Array:
* a)  Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])
* b)  Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [6]:
import numpy as np

arr = np.array([1, 2, 3, 6, 4, 5])
print(np.flip(arr))

[5 4 6 3 2 1]


In [16]:
import numpy as np

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])

most_frequent = np.bincount(x).argmax()
indices = np.where(x == most_frequent)[0]

print("Most Frequent Value:", most_frequent)
print("Indices:", indices)

Most Frequent Value: 1
Indices: [0 5 7 8 9]


In [15]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

most_frequent_value = np.bincount(y).argmax()
indices = np.where(y == most_frequent_value)[0]

print("Most Frequent Value:", most_frequent_value)
print("Indices:", indices)



Most Frequent Value: 1
Indices: [0 1 2]


# Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access elements using row and column indices as follows:
* a) Access 1st row, 2nd column
* b) Access 3rd row, 1st column

In [17]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print(arr[0][1])
# printing 1st row, 2nd column


print(arr[2][0]) # printing 3rd row, 1st column


20
70


# Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array, shape, total elements, the data type of each element and total number of bytes consumed by the array. Find the transpose of this array using reshape() attribute. Can we do the same with T attribute?

In [18]:
# Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly
# spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
# shape, total elements, the data type of each element and total number of bytes consumed
# by the array. Find the transpose of this array using reshape() attribute. Can we do the same
# with T attribute?\

import numpy as np

badhann = np.linspace(start=10, stop=100, num=25)

print(badhann)

print(np.shape(badhann))

print(np.size(badhann))

print(badhann.dtype)

print(badhann.nbytes)

print(badhann.reshape((25,1)))

transposed = badhann.T
display(badhann.T)





[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
(25,)
25
float64
200
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]


array([ 10.  ,  13.75,  17.5 ,  21.25,  25.  ,  28.75,  32.5 ,  36.25,
        40.  ,  43.75,  47.5 ,  51.25,  55.  ,  58.75,  62.5 ,  66.25,
        70.  ,  73.75,  77.5 ,  81.25,  85.  ,  88.75,  92.5 ,  96.25,
       100.  ])

# Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>> with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean, median, max, min, unique elements. Reshape the array to four rows and three columns and name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three columns and name it as resized_ ucs420_<your_name>>.

In [24]:
import numpy as np
ucs420_ = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])

print(ucs420_.mean()) #mean
# finding median
print(np.median(ucs420_))
print(ucs420_.max())# max
print(ucs420_.min()) # min
print(np.unique(ucs420_)) #unique


43.333333333333336
37.5
90
10
[10 15 20 30 35 40 50 60 70 80 90]


In [33]:
import numpy as np
reshaped_ucs420_ = ucs420_.reshape((4,3))
print('Reshaped: ',reshaped_ucs420_)

resized_ucs420_ = np.resize(ucs420_,(2,3))
print('Resized: ',resized_ucs420_)

Reshaped:  [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized:  [[10 20 30]
 [40 50 60]]
