In [2]:
import numpy as np


In [3]:
myarr = np.array([[3,6,9,12,15]])
print(myarr)

[[ 3  6  9 12 15]]


In [4]:
myarr = np.array([[3,6,9,12,15]])  # 2D array (1 row, 5 columns)
# print(myarr.shape)  # Output: (1, 5)

print(myarr[0,1])  # ✅ Correct indexing
print(myarr.shape)

6
(1, 5)


In [5]:
print(myarr.shape)
print(myarr.dtype)

(1, 5)
int64


In [6]:
identity = np.eye(9)  #special numpy function to print the identity matrix
print(identity)

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


## Indexing & Slicing


In [7]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[2,2]) ##indexing

print(arr[:,2])  #slicing

9
[3 6 9]


## MATHEMATICAL OPERATIONS
* NumPy makes element-wise operations super easy!


In [8]:
arr_a = np.array([1,2,3])
arr_b = np.array([4,5,6])
arr_c = np.array([7,8,9])

print(arr_a+arr_b+arr_c)
print(arr_a * arr_b * arr_c)
print(arr_a / arr_b)
print(arr_a ** 2)


[12 15 18]
[ 28  80 162]
[0.25 0.4  0.5 ]
[1 4 9]


# Aggregations & Statistics


In [9]:
arr = np.array([1,2,3,4,5,6,7,8,9])

print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))
print(np.min(arr))
print(np.max(arr))
print(np.sum(arr, axis=0)) # Sum along columns: [5 7 9]



5.0
5.0
2.581988897471611
6.666666666666667
1
9
45


In [10]:
arr = np.array([1, 2, 3, 4, 5, 6])
new_arr = arr.reshape(2, 3)  # Reshape to 2x3 matrix

print(new_arr)


print(arr.T)  # Flip rows and columns

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [11]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Vertical stacking
print(np.vstack((a, b)))

# Horizontal stacking
print(np.hstack((a, b)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
